import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import AuthProvider from '@/context/AuthProvider'
import { Toaster } from "sonner";
import './globals.css'


const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["300", "400", "500", "600"],
  display: "swap",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <body
          className={`${poppins.variable} antialiased`}
        >
          
          <AuthProvider>
          {/* <Navbar /> */}
          {children}
          <Toaster />
          </AuthProvider>
        </body>
    </html>
  );
}
